"use strict";
exports.__esModule = true;
var http = require("http");
var app_1 = require("./app");
var Utils_1 = require("./class/Utils");
var dotenv = require("dotenv");
dotenv.config();
var server = http.createServer(app_1["default"]);
var utils = new Utils_1["default"](server);
var port = utils.normalizePort(process.env.PORT || '3000');
server.on("error", utils.errorHandler);
server.on("listening", function () { return utils.logHandler(port); });
server.listen(port);
