"use strict";
exports.__esModule = true;
var express = require("express");
var ProductController_1 = require("../controller/ProductController");
var Auth_1 = require("../middleware/Auth");
var multer_config_1 = require("../middleware/multer-config");
var router = express.Router();
var controller = new ProductController_1["default"];
router.get("/:id", Auth_1["default"]._verifAuth, controller.findOne);
router.get("/", Auth_1["default"]._verifAuth, controller.find);
;
router.post("/", Auth_1["default"]._verifAuth, multer_config_1["default"], controller.save);
router.put("/:id", Auth_1["default"]._verifAuth, multer_config_1["default"], controller.update);
router["delete"]("/:id", Auth_1["default"]._verifAuth, controller["delete"]);
exports["default"] = router;
